### ISSUE TITLE
Publish npmjs.com

### ISSUE THREAD

**Issue by mryhryki** [mryhryki/simple-encryption#3]
## Task
- [x] Build to ES Module
    - https://zenn.dev/arark/articles/cc58ba9bb79d80ec9cd3
- [x] Test by packed tarball on Node.js
- [x] Publish to npmjs.com by CI (GitHub Actipns)
- [x] Publish with Type definition files
